/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kig_billiardsguide_MainActivity */

#ifndef _Included_com_example_kig_billiardsguide_MainActivity
#define _Included_com_example_kig_billiardsguide_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_kig_billiardsguide_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_example_kig_billiardsguide_MainActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_kig_billiardsguide_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT jintArray JNICALL Java_com_example_kig_billiardsguide_imageanalysis_ImageBinarize
  (JNIEnv *env, jobject, jlong addrInputImage, jlong addrOutputImage, jlong addrPoolImage, jlong addrYbImage, jlong addrWbImage, jlong addrRbImage, jint hitball,
   jlong addrOutputImage1, jlong addrOutputImage2, jlong addrOutputImage3, jlong addrOutputImage4, jlong addrOutputImage5, jlong addrOutputImage6, jlong addrOutputImage7,
   jlong addrOutputImage8, jlong addrOutputImage9
  );

#ifdef __cplusplus
}
#endif
#endif
